### ISSUE TITLE
中文说明勘误

### ISSUE THREAD

**Issue by LeonSec** [XuanwuAI/SecEval#1]
<img width="149" alt="中文" src="https://github.com/XuanwuAI/SecEval/assets/14751632/e1830488-9a7c-4c17-a982-68e4dda7b701">
<img width="233" alt="英文" src="https://github.com/XuanwuAI/SecEval/assets/14751632/59d6968a-c0c7-4f33-8273-f736113435ec">
[https://github.com/XuanwuAI/SecEval/blob/main/README_CN.md](url)
应将<徐建新>变更为<局限性>

**Comment by A7um** [comment]
感谢指出，已修改
